version: '3.1'
services:
  app:
    container_name: todo-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "todo"
      DB_USER: "postgres" 
      DB_PASS: "1234"
      PORT: 5000
      ACCESS_TOKEN_LIFETIME_IN_SEC: 300
      REFRESH_TOKEN_LIFETIME_IN_SEC: 86400
    ports:
      - "5000:5000"
    volumes:
      - "./logs:/var/log/"
      - "./config/jwt:/var/conf/jwt/"
    depends_on: 
      - db
  db:
    container_name: todo-db
    image: postgres:11
    ports:
      - "5433:5432"
    # command: postgres -c log_statement=all
    volumes:
      - "./migrations/db:/docker-entrypoint-initdb.d/"
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "todo"